name: line-ex-messaging-api
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - ".github/workflows/line-ex-messaging-api.yaml"
      - "line_ex_messaging_api/**"
      - "!line_ex_messaging_api/README.md"
defaults:
  run:
    working-directory: line_ex_messaging_api
strategy:
  matrix:
    elixir:
      - 1.12
      - 1.13
    otp:
      - 23
      - 24
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ matrix.otp }}
          elixir-version: ${{ matrix.elixir }}
      - run: mix deps.get
      - run: mix test

  format-checked:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ matrix.otp }}
          elixir-version: ${{ matrix.elixir }}
      - run: mix deps.get
      - run: mix format --check-formatted
